### ISSUE TITLE
Installation Medium freezed

### ISSUE THREAD

**Issue by TeoConan** [archcraft-os/archcraft#45] opened 2020-09-22 09:28 UTC
Hello, I tried archcraft on a live USB stick but my computer got freezed at every boots.

_Here what I only see_
![image](https://user-images.githubusercontent.com/22664730/93865164-3d46dd80-fcc6-11ea-81bc-9a9646684328.png)

I can access to the TTY and system seems to be normal but I cannot do anything...

If someone have an idea or something...
Thank you !

**Comment by ShreyashVerma01** [comment] 2020-09-24 08:15
It works for me but whenever i try to install archcraft and say yes to the clone installer the whole systems crashes and hangs. I have to force shut my laptop then try again only to get the same result.

**Comment by joshg253** [comment] 2020-09-29 17:41
Dupe of #43

**Comment by adi1090x** [comment] 2020-12-31 20:11
Fixed

**Closed by adi1090x** 2020-12-31 20:11 UTC
